# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  schedule:
  # each first day of month
  - cron: "0 0 1 * *"
  push:
  pull_request:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package jib:dockerBuild verify --file pom.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@5a605bd92782ce0810fa3b8acc235c921b497052 # v5.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: atruvia/bundesliga-tabelle

    - name: Upload Cucumber report
      uses: actions/upload-artifact@v4
      if: (success() || failure()) && github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'  # run this step even if previous step failed
      continue-on-error: true
      with:
        name: Cucumber report
        path: target/cucumber-html-reports/

    - name: Test Report
      uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1
      if: (success() || failure()) && github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'  # run this step even if previous step failed
      with:
        name: Tests Report
        path: target/*-reports/TEST-*.xml
        reporter: java-junit

